# Generated by Django 3.2.10 on 2022-05-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='phonenumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
