# Generated by Django 3.2.10 on 2022-05-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_editor_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='articles/default.png', upload_to='articles/'),
        ),
    ]
